#ifndef EN
#define ES
#endif

#ifdef EN
  P(Form_input_send) = "<input type=\"submit\" value=\"Save\">";
  P(Form_input_exec) = "<input type=\"submit\" value=\"Execute\">";
  P(Ent_ana) = "Analog Inputs";
  P(Ent_dig) = "Digital Inputs";
  P(Dev_433) = "Device";
  P(Sal_dig) = "Digital Outputs";
  P(general) = "General";  
  P(opc01) = "<th>Panel</th>";             
  P(opc11) = "<td><a href=\\>Panel</a></td>";
  P(opc02) = "<th>Programming</th>";      
  P(opc12) = "<td><a href=\"sprg.html\">Programming</a></td>";
  P(opc021) = "<th>Weekly</th>";          
  P(opc121) = "<td><a href=\"sse.html\">Weekly</a></td>";
  P(opc022clima) = "<th>Heating Floor</th>";          
  P(opc022) = "<th>Events</th>";          
  P(opc122) = "<td><a href=\"sv.html\">Events</a></td>";
  P(opc122clima) = "<td><a href=\"sclima.html\">Heating Floor</a></td>";
  P(opc023) = "<th>Dates</th>";           
  P(opc123) = "<td><a href=\"sf.html\">Dates</a></td>";
  P(opc024) = "<th>Scenes</th>";          
  P(opc124) = "<td><a href=\"sesc.html\">Scenes</a></td>";
  P(opc025) = "<th>Programs</th>";          
  P(opc125) = "<td><a href=\"sprg.html\">Programs</a></td>";
  P(opc03) = "<th>Setup</th>";     
  P(opc13) = "<td><a href=\"sd.html\">Setup</a></td>";
  P(opc030) = "<th>Device</th>";      
  P(opc130) = "<td><a href=\"sd.html\">Device</a></td>";
  P(opc031) = "<th>Temp. probes</th>";     
  P(opc131) = "<td><a href=\"st.html\">Temp. probes</a></td>";
  P(opc033) = "<th>Net</th>";              
  P(opc133) = "<td><a href=\"sNe.html\">Net</a></td>";
  P(opc035) = "<th>Security</th>";        
  P(opc135) = "<td><a href=\"ss.html\">Security</a></td>";
  P(opc036) = "<th>Date/Time</th>";       
  P(opc136) = "<td><a href=\"srl.html\">Date/Time</a></td>";
  P(opc037) = "<th>Analog. inputs</th>";     
  P(opc137) = "<td><a href=\"sea.html\">Analog. inputs</a></td>";
  P(opc038) = "<th>Digital inputs</th>";   
  P(opc038clima) = "<th>Thermostats</th>";   
  P(opc138) = "<td><a href=\"sed.html\">Digital inputs</a></td>";
  P(opc138clima) = "<td><a href=\"sed.html\">Thermostats</a></td>";
  P(opc039) = "<th>Digital outputs</th>";   
  P(opc139) = "<td><a href=\"ssd.html\">Digital outputs</a></td>";
  P(opc03a) = "<th>My Links</th>";   
  P(opc13a) = "<td><a href=\"slinks.html\">My Links</a></td>";
  P(opc04) = "<th>Avanced</th>";          
  P(opc14) = "<td><a href=\"sa.html\">Avanced</a></td>";
  P(opc041) = "<th>Show logs</th>";    
  P(opc141) = "<td><a href=\"slogs.html\">Show logs</a></td>";
  P(opc042) = "<th>SD files</th>"; 
  P(opc142) = "<td><a href=\"sfiles.html\">SD files</a></td>";
  P(opc043) = "<th>Dump EEPROM</th>";       
  P(opc143) = "<td><a href=\"sy.html?act=shee\">Dump EEPROM</a></td>";
  P(opc044) = "<th>Reset</th>";    
  P(opc144) = "<td><a href=\"rst.html\">Reset</a></td>";
  P(opc045) = "<th>Backup</th>";    
  P(opc145) = "<td><a href=\"sy.html?act=backup\">Backup</a></td>";
  P(opc046) = "<th>Restore</th>";    
  P(opc146) = "<td><a href=\"sy.html?act=restore\">Restore</a></td>";
  P(opc051) = "<th>Radio</th>";            
  P(opc151) = "<td><a href=\"sRa.html\">Radio</a></td>";
  P(opc072) = "<th>Devices</th>";     
  P(opc073) = "<th>Read Code</th>";    
  P(opc08) = "<th>Heat Pump Setup</th>";
  P(opc18)= "<td><a href=\"hpsetup1.html\">Heat Pump Setup</a></td>";
  P(opc081) = "<th>Nivel 1</th>"  ;
  P(opc181)= "<td><a href=\"hpsetup1.html\">Nivel 1</a></td>";
  P(opc082) = "<th>Nivel 2</th>"  ;
  P(opc182)= "<td><a href=\"hpsetup2.html\">Nivel 2</a></td>";
  P(opc083) = "<th>Nivel 3</th>"  ;
  P(opc183)= "<td><a href=\"hpsetup3.html\">Nivel 3</a></td>";
  P(opc09) = "<th>Estado Bomba Calor</th>";
  P(opc19)= "<td><a href=\"estadobc.html\">Estado Bomba Calor</a></td>";
  P(sN) = "Show pin number";
  P(debugserie) = "Serial port debug";
  P(periodoact) = "Refresh period (0-255 seg.)";
  P(MAC) = "MAC (hex.)";
  P(DIRIP) = "IP address";
  P(SUBNET) = "Subnet mask";
  P(GATEWAY) = "Gateway";
  P(DNS_SERVER) = "DNS";
  P(WEB_PORT) = "Webserver port (1-65535)";
  P(smtpPER) = "Period sending mail (min.)";
  P(smtpSVR) = "SMTP server";
  P(smtpPORT) = "SMTP port";
  P(smtpUSER) = "SMTP user";
  P(smtpPASS) = "SMTP password";
  P(smtpREMI) = "Sender";
  P(smtpDEST1) = "Receiver 1";
  P(smtpDEST2) = "Receiver 2";
  P(smtpDEST3) = "Receiver 3";
  P(smtpDEST4) = "Receiver 4";
  P(smtpDEST5) = "Receiver 5";
  P(actenviomail) = "Enable mail";
  P(radCanal) = "Channel";
  P(reactrad) = "Reenvío automático (min.)";
  P(radNodo) = "Node code (OCT)";
  P(radActiva) = "Enable radio";
  P(radFuncion) = "Mode";
  P(radVelocidad) = "Data rate";
  P(red) = "Net";  
  P(redradio) = "Net radio ";
  P(Nodo) = "Node";
  P(nodooct) = "Node(OCT)";
  P(pin) = "Pin";
  P(resetsystem) = "Reset";  
  P(rtcparado) = "RTC stopped";
  P(rtcnodisponible) = "RTC unavailable";
  P(senal) = "Signal";
  P(activo) = "Enabled";
  P(desactivado) = "Disabled";    
  P(ab) = "A/B";
  P(hist) = "Hist.";
  P(accion) = "Action";
  P(fichnoexiste) = "File does not exist";
  P(fichborrado) = "File deleted";
  P(mostrar) = "Show";
  P(desc) = "Descr.";
  P(descripcion) = "Description";
  P(unid) = "Units";
  P(si) = "Yes";
  P(no) = "No";
  P(programa)="Program";
  P(nombre) = "Name";
  P(L) = "Mo";
  P(M) = "Tu";
  P(X) = "We";
  P(J) = "Th";
  P(V) = "Fr";
  P(S) = "Sa";
  P(D) = "Su";
  P(domingo)="Sunday";
  P(lunes)="Monday";
  P(martes)="Tuesday";
  P(miercoles)="Wednesday";
  P(jueves)="Thursday";
  P(viernes)="Friday";
  P(sabado)="Saturday";
  P(enero)="January";
  P(febrero)="February";
  P(marzo)="Mars";
  P(abril)="April";
  P(mayo)="May";
  P(junio)="June";
  P(julio)="July";
  P(agosto)="August";
  P(septiembre)="September";
  P(octubre)="October";
  P(noviembre)="November";
  P(diciembre)="December";
  P(hora) = "Hour";
  P(minuto) = "Min.";
  P(cond) = "Cond.";
  P(acttarjetaSD) = "Enable SD card";
  P(operacionrealizada)= "Operation performed";            
  P(volcadoeeprom) = "DUMP EEPROM";            
  P(noautorizado) = "You are not authorized";  
  P(sondatemp)="Temperature probe ";
  P(entana)="Analog input ";
  P(saldig)="Digital output ";
  P(salrel)="Relay output ";
  P(entdig)="Digital input ";
  P(termostatos)="Thermostats ";
  P(tipo)="Type";
  P(ver)="Show";
  P(nodoactual)="Current node: ";
  P(canalactual)="Current channel: ";
  P(encontrado)=" FOUND ";
  P(noencontrado)=" NOT found ";
  P(estenodo)=" (this node)";
  P(hijo)=" (direct descendent)";
  P(descendiente)=" (descendent)";
  P(padre)=" (ascendent)";
  P(salida)="Output";
  P(fecha)="Date";
  P(fechahora)="Date/Hour";
  P(mes)="Month";
  P(ano)="Year";
  P(dia)="Day";
  P(dias)="Days";
  P(condicion)="Condition";
  P(sincondicion)=">(255)-unconditionally";
  P(diasemana) = "Day of the week";
  P(diamesano) = "Day/Mont/Year";
  P(horaminseg) = "Hour:Min:Seg";
  P(valor)="Value";
  P(Sal_rel)="Relay outputs";      
  P(sonda)="Probe ";     
  P(enta)="An.Inp. ";     
  P(entd)="Dig.Inp. ";     
  P(sald)="Dig.Out. ";     
  P(rele)="Relay ";     
  P(sondastemperatura)="Temperature probes";  
  P(panel)="Panel";
  P(edigitales)="Digital inputs";
  P(eanalogicas)="Analog inputs";
  P(sdigitales)="Digital/relays outputs";
  P(Ent_temp)="Temperatures";
  P(activarcontrasena) = "Enable auth";
  P(servidor)="Server";
  P(puerto)="Port";
  P(noconectado)="NOT CONNECTED";        
  P(evento)="Event";  
  P(disparador)="Input signal";
  P(senalsalida)="Output signal";
  P(dig)="Dig.";
  P(ana)="Temperature/Value";
  P(contrasena)="Password";
  P(confcontrasena)="Confirm password";
  P(compa)="Comp.";
  P(dispositivo)="Device";
  P(taddress)="Addr/Syst/Code ON";
  P(tcodeoff)="Code OFF";
  P(tunit)="Unit/Dev./OFF";
  P(emisor)="Emitter";
  P(actuador)="Actuator";
  P(emisoractuador)="Emitter/Actuator";
  P(generico)="GENERIC";
  P(genericonuevo)="GENERIC NEW";
  P(marcaclase)="Brand/Kind";
  P(lor)="L/R";
  P(Local)="Local";
  P(Act)="Act.";
  P(precisionsondas)="Probes accuracy (bits)";
  P(factor)="Factor";
  P(escena)="Scene ";  
  P(escena1)="Scene 1";  
  P(escena2)="Scene 2";  
  P(escena3)="Scene 3";  
  P(escena4)="Scene 4";  
  P(escena5)="Scene 5";  
  P(avanzado)="Avanced";    
  P(basico)="Basic";    
  P(local)="Local";    
  P(domotica)="Home automation";    
  P(riego)="Irrigation";    
  P(climatizacion)="HVAC control";
  P(Modo)="Mode";  
  P(asociaraprograma)="Associate to program";
  P(dyndnsserv)="DDNS service";
  P(dyndnshost)="DDNS domain";
  P(dyndnsuser)="DDNS user";
  P(dyndnspass)="DDNS password";
  P(estaventanaseactualizacada3segundos)="This window is updated every 3 seconds";
  P(nodejarestaventanaabierta)="DO NOT LEAVE THIS WINDOW OPENED";
  P(ultrecibido)="Last code received: ";
  P(ficheronoencontrado)="File not found";
  P(sistema)="System";
  P(acciones)="Actions";
  P(eventos)="Events";
  P(vereventos)="<td><a href=\"sf?eventos.log\">View</a></td>";
  P(deleventos)="<td><a href=\"df?eventos.log\">Delete</a></td>";
  P(versistema)="<td><a href=\"sf?system.log\">View</a></td>";
  P(delsistema)="<td><a href=\"df?system.log\">Delete</a></td>";
  P(veracciones)="<td><a href=\"sf?acciones.log\">View</a></td>";
  P(delacciones)="<td><a href=\"df?acciones.log\">Delete</a></td>";
  P(verEnt_temp)="<td><a href=\"sf?temperat.log\">View</a></td>";
  P(delEnt_temp)="<td><a href=\"df?temperat.log\">Delete</a></td>";
  P(verEnt_ana)="<td><a href=\"sf?analog.log\">View</a></td>";
  P(delEnt_ana)="<td><a href=\"df?analog.log\">Delete</a></td>";
  P(tmactVar)="Log Temp. period (0-65535 seg)";
  P(ninguno)="None";
  P(lcdHitachiHD44780)="Hitachi HD44780";
  P(lcdPowertipPC4004)="Powertip PC4004";
  P(ttipoLCD)="LCD type";
  // 30/3/2014
  P(libre)="Free:";
  P(blancoNodo)=" Nodo:";
  P(blancoPeriodo)=" Period:";
  P(blancoCdospuntos)=" C:";
  P(espere)="Wait...(about 180 sec.)";
  P(espereinit)="Init.  Wait...(about 180 sec.)";
  P(conucoweb)="REGULADOR UNIVERSAL BC, v.";
  P(lanip)="LAN IP:";
  P(blancogw)=" GW:";
  P(blanco1wp1)="1Wire-PORT 1:";
  P(blanco1wp2)="1Wire-PORT 2:";
  P(blancomodo)=" Mode:";
  P(parasite)="Parasite";
  P(power)="Power";
  P(tSD)="SD ";
  P(Ok)="Ok";
  P(OK)="Ok ";
  P(NO)="NO";
  P(inic)="Init.:";
  P(iniciando)="Initiating";
  P(parado)="stopped";
  P(mailALARMA)="ALARM, ";
  P(mailHaPasadoa)="\" ha pasado a ";
  P(mailhasuperado)="\" ha superado o ha bajado del umbral fijado de ";     
  P(mailsonda)=" Probe \"";
  P(mailvaloract)=" C. Current value: ";      
  P(linkusuario)="User's link ";
  P(usuario)="User";
  P(contrasenaguardada)="Pasword enabled";    
  P(contrasenanocoincide)="Passwords do not match. Password disabled";    
  P(contrasenaincorrecta)="Incorrect password";    
  P(urltext)="URL";
  P(erroralguardar)="Error al hacer copia de seguridad";
  P(borrar)="Delete";
  P(offset)="Offset";
  P(reintentos)="N. Retry";
  P(hecho)="Done";
  P(explorar)="Explore";
  P(probarnodo)="Test node";
  P(ttimeout)="Timeout (ms)";
  P(ficheroguardado)="File saved: ";
  P(ficherorecuperado)="File restored: ";
  P(tmactRem)="Polling period (s)";
  P(blancoSondas)=" Probes";
  P(nodosusados)="Used nodes:";
  P(preciokwh)="Price kwh";
  P(blancosondas)=" Probes:";
  P(SDrele)=" SD/Relay ";
  P(blancop)=" Pin:";
  P(blancov)=" Value:";
  P(blancosonda)=" Probe:";
  P(blancoaddr)=" Addr:";
  P(nodisponible)="N/A";
  P(circuito)="Circuit";
  P(termostato)="Thermostat";
  P(tipocodigo)="Code type: ";
  P(DIOmode)=" CHACON D-IO, GENERIC NEW";
  P(DEMAmode)=" DEMA, GENERIC OLD";
  P(tiposugerido)="Suggested type: ";
  P(sumat)="Σ";
  P(resetfabrica)="Factory reset";
  P(avisoresetfab)="THIS OPTION WILL DELETE ALL DATA!";
  P(nodo433)=" Node 433:"; 
  P(encryption)="Encryption";
  P(version)="Version";
  P(APcontrasena)="AP password";
  P(comprobando)="Verifiyng...wait";
  P(bombacalor)="Heat Pump Setup";
#endif

#ifdef ES
  P(Form_input_send) = "<input type=\"submit\" value=\"Guardar\">";
  P(Form_input_exec) = "<input type=\"submit\" value=\"Ejecutar\">";
  P(Ent_ana) = "Entradas analógicas";
  P(Ent_dig) = "Entradas digitales";
  P(Dev_433) = "Dispositivo";
  P(Sal_dig) = "Salidas digitales";
  P(general) = "General";  
  P(opc01) = "<th>Panel</th>";             
  P(opc11) = "<td><a href=\\>Panel</a></td>";
  P(opc02) = "<th>Programación</th>";      
  P(opc12) = "<td><a href=\"sprg.html\">Programación</a></td>";
  P(opc021) = "<th>Semanal</th>";          
  P(opc121) = "<td><a href=\"sse.html\">Semanal</a></td>";
  P(opc022) = "<th>Eventos</th>";          
  P(opc022clima) = "<th>Suelo radiante</th>";          
  P(opc122) = "<td><a href=\"sv.html\">Eventos</a></td>";
  P(opc122clima) = "<td><a href=\"sclima.html\">Suelo radiante</a></td>";
  P(opc023) = "<th>Fechas</th>";           
  P(opc123) = "<td><a href=\"sf.html\">Fechas</a></td>";
  P(opc024) = "<th>Escenas</th>";          
  P(opc124) = "<td><a href=\"sesc.html\">Escenas</a></td>";
  P(opc025) = "<th>Programas</th>";          
  P(opc125) = "<td><a href=\"sprg.html\">Programas</a></td>";
  P(opc03) = "<th>Configuración</th>";     
  P(opc13) = "<td><a href=\"sd.html\">Configuración</a></td>";
  P(opc030) = "<th>Dispositivo</th>";      
  P(opc130) = "<td><a href=\"sd.html\">Dispositivo</a></td>";
  P(opc031) = "<th>Sondas Temp.</th>";     
  P(opc131) = "<td><a href=\"st.html\">Sondas Temp.</a></td>";
  P(opc033) = "<th>Red</th>";              
  P(opc133) = "<td><a href=\"sNe.html\">Red</a></td>";
  P(opc035) = "<th>Seguridad</th>";        
  P(opc135) = "<td><a href=\"ss.html\">Seguridad</a></td>";
  P(opc036) = "<th>Fecha/Hora</th>";       
  P(opc136) = "<td><a href=\"srl.html\">Fecha/Hora</a></td>";
  P(opc037) = "<th>Ent. Analog.</th>";     
  P(opc137) = "<td><a href=\"sea.html\">Ent. Analog.</a></td>";
  P(opc038) = "<th>Ent. Digitales</th>";   
  P(opc038clima) = "<th>Termostatos</th>";   
  P(opc138) = "<td><a href=\"sed.html\">Ent. Digitales</a></td>";
  P(opc138clima) = "<td><a href=\"sed.html\">Termostatos</a></td>";
  P(opc039) = "<th>Sal. Digitales</th>";   
  P(opc139) = "<td><a href=\"ssd.html\">Sal. Digitales</a></td>";
  P(opc04) = "<th>Avanzado</th>";          
  P(opc14) = "<td><a href=\"sa.html\">Avanzado</a></td>";
  P(opc041) = "<th>Ver Históricos</th>";    
  P(opc141) = "<td><a href=\"slogs.html\">Ver Históricos</a></td>";
  P(opc042) = "<th>Ficheros SD</th>"; 
  P(opc142) = "<td><a href=\"sfiles.html\">Ficheros SD</a></td>";
  P(opc043) = "<th>Ver EEPROM</th>";       
  P(opc143) = "<td><a href=\"sy.html?act=shee\">Ver EEPROM</a></td>";
  P(opc044) = "<th>Reset</th>";    
  P(opc144) = "<td><a href=\"rst.html\">Reset</a></td>";
  P(opc045) = "<th>Backup</th>";    
  P(opc145) = "<td><a href=\"sy.html?act=backup\">Backup</a></td>";
  P(opc046) = "<th>Restore</th>";    
  P(opc146) = "<td><a href=\"sy.html?act=restore\">Restore</a></td>";
  P(opc08) = "<th>Conf. Bomba Calor</th>";
  P(opc18)= "<td><a href=\"hpsetup1.html\">Conf. Bomba Calor</a></td>";
  P(opc081) = "<th>Nivel 1</th>"  ;
  P(opc181)= "<td><a href=\"hpsetup1.html\">Nivel 1</a></td>";
  P(opc082) = "<th>Nivel 2</th>"  ;
  P(opc182)= "<td><a href=\"hpsetup2.html\">Nivel 2</a></td>";
  P(opc083) = "<th>Nivel 3</th>"  ;
  P(opc183)= "<td><a href=\"hpsetup3.html\">Nivel 3</a></td>";
  P(opc09) = "<th>Estado Bomba Calor</th>";
  P(opc19)= "<td><a href=\"estadobc.html\">Estado Bomba Calor</a></td>";
  P(sN) = "Mostrar datos pin";
  P(debugserie) = "Depuración puerto serie";
  P(periodoact) = "Per. actualización (0-255 seg.)";
  P(MAC) = "Dirección MAC (hex.)";
  P(DIRIP) = "Dirección IP";
  P(SUBNET) = "Máscara de subred";
  P(GATEWAY) = "Puerta de enlace";
  P(DNS_SERVER) = "Servidor DNS";
  P(WEB_PORT) = "Puerto Webserver (1-65535)";
  P(smtpPER) = "Período envío correos (min.)";
  P(smtpSVR) = "Servidor SMTP";
  P(smtpPORT) = "Puerto SMTP";
  P(smtpUSER) = "Usuario SMTP";
  P(smtpPASS) = "Contraseña SMTP";
  P(smtpREMI) = "Remitente";
  P(smtpDEST1) = "Destinatario 1";
  P(smtpDEST2) = "Destinatario 2";
  P(smtpDEST3) = "Destinatario 3";
  P(smtpDEST4) = "Destinatario 4";
  P(smtpDEST5) = "Destinatario 5";
  P(actenviomail) = "Activar envío correos";
  P(radCanal) = "Canal";
  P(reactrad) = "Reenvío automático (min.)";
  P(radNodo) = "Código de Nodo (OCT)";
  P(radActiva) = "Activar radio";
  P(radFuncion) = "Modo";
  P(radVelocidad) = "Velocidad datos";
  P(red) = "Red";  
  P(redradio) = "Red radio ";
  P(Nodo) = "Nodo";
  P(nodooct) = "Nodo(OCT)";
  P(pin) = "Pin";
  P(resetsystem) = "Reset";  
  P(rtcparado) = "RTC parado";
  P(rtcnodisponible) = "RTC no disponible";
  P(senal) = "Señal";
  P(activo) = "Activo";
  P(desactivado) = "Desactivado";    
  P(ab) = "A/B";
  P(hist) = "Hist.";
  P(accion) = "Acción";
  P(fichnoexiste) = "Fichero no existe";
  P(fichborrado) = "Fichero borrado";
  P(mostrar) = "Mostrar";
  P(desc) = "Descr.";
  P(descripcion) = "Descripción";
  P(unid) = "Unid.";
  P(si) = "Sí";
  P(no) = "No";
  P(programa)="Programa";
  P(nombre) = "Nombre";
  P(L) = "L";
  P(M) = "M";
  P(X) = "M";
  P(J) = "J";
  P(V) = "V";
  P(S) = "S";
  P(D) = "D";
  P(domingo)="Domingo";
  P(lunes)="Lunes";
  P(martes)="Martes";
  P(miercoles)="Miércoles";
  P(jueves)="Jueves";
  P(viernes)="Viernes";
  P(sabado)="Sábado";
  P(enero)="Enero";
  P(febrero)="Febrero";
  P(marzo)="Marzo";
  P(abril)="Abril";
  P(mayo)="Mayo";
  P(junio)="Junio";
  P(julio)="Julio";
  P(agosto)="Agosto";
  P(septiembre)="Septiembre";
  P(octubre)="Octubre";
  P(noviembre)="Noviembre";
  P(diciembre)="Diciembre";
  P(hora) = "Hora";
  P(minuto) = "Min.";
  P(cond) = "Cond.";
  P(acttarjetaSD) = "Activar tarjeta SD";
  P(operacionrealizada)= "Operación realizada";    
  P(volcadoeeprom) = "VOLCADO EEPROM";            
  P(noautorizado) = "No está autorizado";  
  P(nodoact)="Código Nodo actual (OCT)";  
  P(nodoreset)="Código Nodo (OCT)";  
  P(nodonue)="Código Nodo nuevo (OCT)";  
  P(canalact)="Canal actual (1-126)";  
  P(canalnue)="Canal nuevo (1-126)";  
  P(fueraderango)= " fuera de rango.";     
  P(solonodocero)="Solamente es posible desde el nodo 0";
  P(origen)="Origen: ";
  P(destino)=" Destino: ";
  P(noaccesible)=" NO ACCESIBLE";
  P(nodoraiz)="Código Nodo raíz (OCT)";
  P(sondatemp)="Sonda temperatura ";
  P(entana)="Entrada analógica ";
  P(saldig)="Salida digital ";
  P(salrel)="Salida relé ";
  P(entdig)="Entrada digital ";
  P(termostatos)="Termostatos ";
  P(tipo)="Tipo";
  P(ver)="Ver";
  P(encontrado)=" ENCONTRADO ";
  P(noencontrado)=" NO encontrado ";
  P(salida)="Salida";
  P(fecha)="Fecha";
  P(fechahora)="Fecha/Hora";
  P(mes)="Mes";
  P(ano)="Año";
  P(dia)="Día";
  P(dias)="Días";
  P(condicion)="Condición";
  P(sincondicion)=">(255)-Sin Condición";
  P(diasemana) = "Día semana";
  P(diamesano) = "Día/Mes/Año";
  P(horaminseg) = "Hora:Min:Seg";
  P(valor)="Valor";
  P(Sal_rel)="Salidas relé";      
  P(sonda)="Sonda ";     
  P(enta)="E.An. ";     
  P(entd)="E.Dig. ";     
  P(sald)="S.Dig. ";     
  P(rele)="Relé ";     
  P(sondastemperatura)="Sondas de temperatura";  
  P(panel)="Panel";
  P(edigitales)="Entradas digitales";
  P(eanalogicas)="Entradas analógicas";
  P(sdigitales)="Salidas digitales/relés";
  P(Ent_temp)="Temperaturas";
  P(activarcontrasena) = "Activar autenticación";
  P(servidor)="Servidor";
  P(puerto)="Puerto";
  P(noconectado)="NO CONECTADO";        
  P(evento)="Evento";  
  P(disparador)="Señal activadora";
  P(senalsalida)="Señal de Salida";
  P(dig)="Dig.";
  P(ana)="Temperatura/Valor";
  P(contrasena)="Contraseña";
  P(confcontrasena)="Confirme Contraseña";
  P(compa)="Comp.";
  P(dispositivo)="Dispositivo";
  P(taddress)="Addr/Syst/Code ON";
  P(tcodeoff)="Code OFF";
  P(tunit)="Unit/Dev";
  P(emisor)="Emisor";
  P(actuador)="Actuador";
  P(emisoractuador)="Emisor/Actuador";
  P(generico)="GENÉRICO";
  P(genericonuevo)="GENERICO NEW";
  P(marcaclase)="Marca/Clase";
  P(lor)="L/R";
  P(Local)="Local";
  P(Act)="Act.";
  P(precisionsondas)="Precisión sondas (bits)";
  P(factor)="Factor";
  P(escena)="Escena ";  
  P(escena1)="Escena 1";  
  P(escena2)="Escena 2";  
  P(escena3)="Escena 3";  
  P(escena4)="Escena 4";  
  P(escena5)="Escena 5";  
  P(avanzado)="Avanzado";    
  P(basico)="Básico";    
  P(local)="Local";    
  P(domotica)="Domótica";    
  P(riego)="Riego";
  P(climatizacion)="Climatizacion";
  P(Modo)="Modo";  
  P(asociaraprograma)="Asociar a programa";
  P(dyndnsserv)="Servicio DDNS";
  P(dyndnshost)="Dominio DDNS";
  P(dyndnsuser)="Usuario DDNS";
  P(dyndnspass)="Contraseña DDNS";
  P(estaventanaseactualizacada3segundos)="Esta ventana se actualiza cada 3 segundos";
  P(nodejarestaventanaabierta)="NO DEJE ESTA VENTANA ABIERTA";
  P(ultrecibido)="Último código recibido: ";
  P(ficheronoencontrado)="Fichero no encontrado";
  P(sistema)="Sistema";
  P(acciones)="Acciones";
  P(eventos)="Eventos";

  P(vereventos)="<td><a href=\"sf?eventos.log\">Ver</a></td>";
  P(deleventos)="<td><a href=\"df?eventos.log\">Borrar</a></td>";
  P(versistema)="<td><a href=\"sf?system.log\">Ver</a></td>";
  P(delsistema)="<td><a href=\"df?system.log\">Borrar</a></td>";
  P(veracciones)="<td><a href=\"sf?acciones.log\">Ver</a></td>";
  P(delacciones)="<td><a href=\"df?acciones.log\">Borrar</a></td>";
  P(verEnt_temp)="<td><a href=\"sf?temperat.log\">Ver</a></td>";
  P(delEnt_temp)="<td><a href=\"df?temperat.log\">Borrar</a></td>";
  P(verEnt_ana)="<td><a href=\"sf?analog.log\">Ver</a></td>";
  P(delEnt_ana)="<td><a href=\"df?analog.log\">Borrar</a></td>";
  P(tmactVar)="Período log temperaturas (0-255 seg)";
  P(ninguno)="Ninguno";
  P(lcdHitachiHD44780)="Hitachi HD44780";
  P(lcdPowertipPC4004)="Powertip PC4004";
  P(ttipoLCD)="Tipo LCD";
  // 30/3/2014
  P(libre)="Libre:";
  P(blancoNodo)=" Nodo:";
  P(blancoPeriodo)=" Periodo:";
  P(blancoCdospuntos)=" C:";
  P(espere)="Espere...(unos 180 seg.)";
  P(espereinit)="Iniciando.   Espere...(unos 180 seg.)";
  P(conucoweb)="REGULADOR BC, v.";
  P(lanip)="LAN IP:";
  P(blancogw)=" GW:";
  P(rf24vel)="RF24 Vel:"; 
  P(blancocanal)=" Canal:";
  P(blancopsize)=" PSize:";
  P(blancocrcl)=" CRCL:";
  P(blancolevel)=" Level:";
  P(blnacorfnet)="RFNET Nodo:";
  P(blanco1wp1)="1Wire-Port 1:";
  P(blanco1wp2)="1Wire-Port 2:";
  P(blancomodo)=" Modo:";
  P(parasite)="Parasite";
  P(power)="Power";
  P(tSD)="SD ";
  P(Ok)="Ok";
  P(OK)="Ok ";
  P(NO)="NO";
  P(inic)="Inic.:";
  P(iniciando)="Iniciando";
  P(parado)="parado";
  P(mailALARMA)="ALARMA, ";
  P(mailHaPasadoa)="\" ha pasado a ";
  P(mailhasuperado)="\" ha superado o ha bajado del umbral fijado de ";     
  P(mailsonda)=" Sonda \"";
  P(mailvaloract)=" C. Valor actual: ";    
  P(linkusuario)="Enlace usuario ";
  P(usuario)="Usuario";
  P(contrasenaguardada)="Contraseña guardada";    
  P(contrasenanocoincide)="Contraseñas no coinciden. Contraseña desactivada.";    
  P(contrasenaincorrecta)="Contraseña incorrecta";    
  P(urltext)="URL";
  P(erroralguardar)="Error al hacer copia de seguridad";
  P(borrar)="Borrar";
  P(offset)="Offset";
  P(reintentos)="Reintentos";
  P(hecho)="Hecho";
  P(explorar)="Explorar";
  P(probarnodo)="Probar nodo";
  P(ttimeout)="Tiempo espera (ms)";
  P(ficheroguardado)="Fichero guardado: ";
  P(ficherorecuperado)="Fichero recuperado: ";
  P(tmactRem)="Perído polling (seg.)";
  P(blancoSondas)=" Sondas";
  P(nodosusados)="Nodos utilizados:";
  P(preciokwh)="Precio kwh";
  P(blancosondas)=" Sondas:";
  P(SDrele)=" SD/Rele ";
  P(blancop)=" Pin:";
  P(blancov)=" Valor:";
  P(blancosonda)=" Sonda:";
  P(blancoaddr)=" Addr:";
  P(nodisponible)="N.D.";
  P(circuito)="Circuito";
  P(termostato)="Termostato";
  P(tipocodigo)="Tipo código: ";
  P(sumat)="Σ";
  P(resetfabrica)="Reset fábrica";
  P(avisoresetfab)="¡ESTA OPCIÓN BORRARÁ TODOS LOS DATOS!";
  P(nodo433)=" Nodo 433:"; 
  P(encryption)="Encryption";
  P(version)="Versión";
  P(APcontrasena)="AP contraseña";
  P(comprobando)="Comprobando...espere";
  
  P(bombacalor)="Conf. Bomba calor";
  P(estacion)="Estación";
  P(invierno)="Invierno";
  P(verano)="Verano";
P(t1)="Temperatura exterior mínima (T1)";
P(t2)="Temperatura exterior máxima (T2)";
P(t3)="Temperatura retorno máxima (T3)";
P(t4)="Temperatura retorno mínima (T4)";
P(c)="Temporización Bomba Calef. (C)";
P(cc)="Temporización Bomba Captador (CC)";
P(ccc)="Temporización Compresor (CCC)";
P(acs)="Consigna ACS (ACS)";
P(frio)="Consigna Frío (FRo)";
P(pis)="Consigna piscina (PIS)";
P(res)="Consigna resistencia (RES)";
P(cr1)="Temporización resistencia (Cr1)";
P(cr2)="Temporización comp. resistencia (Cr2)";
P(aoc)="Consigna mezcla Calor (AoC)";
P(aof)="Consigna mezcla Frío (AoF)";
P(histcalefaccion)="Histéresis Calefacción (HYC)";
P(histfrio)="Histéresis Frío (HYF)";
P(histacs)="Histéresis ACS (HYA)";
P(histpiscina)="Histéresis Piscina (HYP)";
P(histresistencia)="Histéresis Resistencia (HYR)";
P(bandaprop)="Rango válvula mezcladora (bPC)";
P(limiteah2)="Límite temperatura impulsión (AH2)";
P(limiteah4)="Límite máximo temperatura (AH4)";
P(protcapafre)="Protección capa freática(Ab4)";
P(limitepiscina)="Temperatura máxima piscina (tLP)";
P(modoeco)="Modo ECO";
P(tiempooff)="Duración apagado (h)";
P(tiempoon)="Duración arranque (min)";
P(secadomortero)="Secado mortero";
P(tempini)="Temperatura inicial";
P(tempfin)="Temperatura final";
P(nbh)="Número de horas";
P(apoyo)="Utilizar Apoyo";
P(consignacalor)="Consigna calor";
P(consignafrio)="Consigna frío";
P(consignapiscina)="Consigna piscina";
P(segdesdeinireg)="Arranque Regulador (s)";
P(segdesdeinibcal)="Arranque bomba circulación (s)";
P(segdesdeinibcap)="Arranque bomba captador (s)";
P(segdesdeinicomp)="Arranque compresor (s)";
P(segdesdefincomp)="Parada compresor (s)";
P(segdesalarmatemp)="Segundos alarma temporizada";
P(valoresinternos)="VALORES INTERNOS";
P(reles)="RELÉS";
P(rbombacal)="Bomba Calefacción";
P(rbombacap)="Bomba Captador";
P(rcompresor)="Compresor";
P(racs)="ACS";
P(rv3v)="Válvula 3 vías";
P(rresistencia)="Resistencia";
P(rv4v)="Válvula 4 vías";
P(ralarma)="Alarma";

P(entradasdigitales)="ENTRADAS DIGITALES";
P(presostatoalta)="Presostato Alta P";
P(presostatobaja)="Presostato Baja P";
P(fluxostatocal)="Fluxostato Calefacción";
P(fluxostatocap)="Fluxostato Captador";
P(fluxostatocf)="Fluxostato Capa freática";
P(contactofiltro)="Contacto filtración";
P(contactoacs)="Contacto ACS";
P(contactofrio)="Contacto Frío";
P(contactopiscina)="Contacto Piscina";
P(contactoonoff)="ON/OFF";
P(estado)="Estado";
P(Parado)="PARADO";
P(standby)="Standby";
P(fase1)="Fase 1";
P(fase2)="Fase 2";
P(fase3)="Fase 3";
P(running)="FUNCIONANDO";
P(calentando)="CALENTANDO";
P(enfriando)="ENFRIANDO";
P(calepiscina)="CALENTANDO PISCINA";
P(tempcompresoroff)="TEMPORIZA COMP.OFF";
P(alarma)="ALARMA";
P(retcalefaccion)="Ret. Calefacción";
P(idacalefaccion)="Ida Calefacción";
P(retcaptador)="Ret. Captador";
P(idacaptador)="Ida Captador";
P(sondaexterior)="Sonda Exterior";
P(sondaauxiliar)="Sonda auxiliar";
P(tcalor)="Calefacción";
P(tfrio)="Frío";
P(tacs)="ACS";
P(tpiscina)="Piscina";
P(lcdcal)="Cal";
P(lcdfri)="Fri";
P(lcdacs)="ACS";
P(lcdpis)="Pis";
P(lcdala)="AL: ";
P(lcdbc1)="bc1";
P(lcdbc2)="bc2";
P(lcdcomp)="COMP";
P(lcdblanco)="    ";
P(lcdblancos)="      ";
P(lcd10blancos)="          ";
P(lcdter)="T";
P(lcdext)="Ext";
P(apagado)="OFF";
P(parametro)="Parametro";
P(lcdestacion)="Estacion";
P(lcdsta)="STA";
P(lcdtt1)="Temp. ext. minima";
P(lcdt1)="T1";
P(lcdtt2)="Temp. ext. maxima";
P(lcdt2)="T2";
P(lcdtt3)="Temp. ret. maxima";
P(lcdt3)="T3";
P(lcdtt4)="Temp. ret. minima";
P(lcdt4)="T4";
P(lcdtc)= "Temp. B. Calef. C";
P(lcdc)="C";
P(lcdtcc)="Temp. B. Captador";
P(lcdcc)="CC";
P(lcdtccc)="Temp. Compresor";
P(lcdccc)="CCC";
P(lcdcacs)="Consigna ACS";
P(lcdfrio)="Consigna Frio";
P(lcdfro)="FRO";
P(lcdcpis)="Consigna piscina";
P(lcdcres)="Consigna resistencia";
P(lcdres)="RES";
P(lcdccr1)="Temp. acti. resist.";
P(lcdcr1)="TCr1";
P(lcdccr2)="Horas comp antes res";
P(lcdcr2)="Cr2";
P(lcdcaoc)="Consigna Calor Mez.";
P(lcdaoc)="AoC";
P(lcdcaof)="Consigna Frio Mez.";
P(lcdaof)="AoF";
P(lcdhistcalefaccion)="Hist. Calefaccion";
P(lcdhyc)="HYC";
P(lcdhistfrio)="Hist. Frio";
P(lcdhyf)="HYF";
P(lcdhistacs)="Hist. ACS";
P(lcdhya)="HYA";
P(lcdhistpiscina)="Hist. Piscina";
P(lcdhyp)="HYP";
P(lcdhistresistencia)="Hist. Resistencia";
P(lcdhyr)="HYR";

P(lcdbandaprop)="Rango valvula mezcl.";
P(lcdbpc)="bPC";
P(lcdlimiteah2)="Lim. temp. impulsion";
P(lcdah2)="AH2";
P(lcdlimiteah4)="Alarma temperatura";
P(lcdah4)="AH4";
P(lcdprotcapafre)="Prot. capa freat.";
P(lcdab4)="Ab4";
P(lcdlimitepiscina)="Temp. max. piscina";
P(lcdtlp)="tLP";
P(lcdmodoeco)="Modo Economico";
P(lcdeco)="ECO";
P(lcdtiempooff)="Duracion OFF (h)";
P(lcdtof)="tOF";
P(lcdtiempoon)="Duracion ON (min)";
P(lcdton)="tOn";
P(lcdsecadomortero)="Secado mortero";
P(lcdpro)="PRO";
P(lcdtempini)="Temperatura inicial";
P(lcdtin)="tIn";
P(lcdtempfin)="Temperatura final";
P(lcdtfi)="tFi";
P(lcdNbh)="Numero de horas";
P(lcdnbh)="nBh";
P(lcdapoyo)="Utilizar Apoyo";
P(lcdapp)="APP";
P(guardando)="Guardando datos";
P(encendido)="Encendido";
P(lcddia)="Dia";
P(lcdmes)="Mes";
P(lcdano)="Ano";
P(lcdhora)="Hora";
P(lcdmin)="Min.";
P(noolvide1)="No olvide guardar";
P(noolvide2)="Pulse la tecla 4";
P(aviso1)="Cambiar parametros";
P(aviso2)="puede afectar a la ";
P(aviso3)="BC o causar averias";
P(aviso4)="ES SU RESPONSABILIDA";
P(avisoAM1)=" SISTEMA BLOQUEADO";
P(avisoAM2)="  Contacte con el ";
P(avisoAM3)="    Instalador";
P(avisoAM4)="";
P(codigo)="Codigo:";
P(activarbloqueo)="Activar bloqueo";
P(desactivarbloqueo)="Desactivar bloqueo";
P(bloqueoactivo)="AM activo";
P(bloqueoinactivo)="AM NO activo";

#endif

